name: Workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
          pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov znakes
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
